# Generated by Django 4.0.4 on 2022-06-30 22:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de categoria')),
                ('nombreCategoria', models.CharField(max_length=50, verbose_name='nombre de la categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rutCliente', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='rut del cliente')),
                ('nombreCliente', models.CharField(max_length=50, verbose_name='nombre del cliente')),
                ('correo', models.EmailField(max_length=50, verbose_name='correo del cliente')),
                ('telefono', models.IntegerField(verbose_name='telefono del cliente')),
                ('direccion', models.CharField(max_length=50, verbose_name='direccion del cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='id del producto')),
                ('nombreProducto', models.CharField(max_length=50, verbose_name='nombre del producto')),
                ('precio', models.IntegerField(verbose_name='precio del producto')),
                ('marca', models.CharField(max_length=50, verbose_name='marca del producto')),
                ('imagen', models.ImageField(upload_to='', verbose_name='imagen del producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsociety.categoria')),
            ],
        ),
    ]
