# Generated by Django 4.0.4 on 2022-07-09 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsociety', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock',
            field=models.IntegerField(default='2', verbose_name='stock del producto'),
        ),
    ]
