# Generated by Django 4.0.4 on 2022-07-10 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petsociety', '0002_producto_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(max_length=30, verbose_name='Estado de pedido')),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaOrden', models.DateField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsociety.cliente', verbose_name='rut Cliente')),
                ('estadoOrden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsociety.estado', verbose_name='Estado Del Pedido')),
            ],
        ),
        migrations.CreateModel(
            name='OrdenProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(blank=True, default=0, null=True, verbose_name='cantidad de producto')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsociety.orden', verbose_name='id de la orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsociety.producto', verbose_name='id Producto')),
            ],
        ),
    ]
