# Generated by Django 4.0.4 on 2022-07-12 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petsociety', '0004_cliente_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='completado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='orden',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='petsociety.cliente', verbose_name='rut Cliente'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estadoOrden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='petsociety.estado', verbose_name='Estado Del Pedido'),
        ),
    ]
