# Generated by Django 4.0.4 on 2022-07-12 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('petsociety', '0006_remove_orden_estadoorden'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
    ]
