# Generated by Django 4.0.4 on 2022-07-16 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('petsociety', '0010_producto_accesorio_alter_categoria_idcategoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproducto',
            name='cantidad',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad De roducto'),
        ),
        migrations.RemoveField(
            model_name='producto',
            name='categoria',
        ),
        migrations.AddField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='petsociety.categoria'),
        ),
    ]
