# Generated by Django 4.0.4 on 2022-07-16 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsociety', '0012_alter_producto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='destacado',
            field=models.BooleanField(default=False, verbose_name='Destacado'),
        ),
    ]
