# Generated by Django 4.0.2 on 2022-06-10 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petsociety', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('rutCliente', models.CharField(max_length=13, primary_key=True, serialize=False, verbose_name='rut del cliente')),
                ('nombreCliente', models.CharField(max_length=50, verbose_name='nombre del cliente')),
                ('correo', models.CharField(max_length=50, verbose_name='correo del cliente')),
                ('telefono', models.IntegerField(verbose_name='telefono del cliente')),
            ],
        ),
    ]
